services:
  server:
    build: ./
    image: returnauf
    container_name: server
    command: ./app
    environment:
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      REDIS_ADDRESS: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DB_ADDRESS: db.sqlite
      API_KEY: ${API_KEY}
    restart: on-failure:5
    networks:
      - app-network
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis/redis-stack-server
    container_name: redis
    restart: on-failure:5
    networks:
      - app-network
    ports:
      - "6379:6379"

networks:
  app-network:
    