services:
  auf-citaty:
    build: ./
    image: auf-citaty
    container_name: auf-citaty
    command: ./auf-citaty
    environment:
      REDIS_ADDRESS: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      DB_DSN: db.sqlite
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      AUF_CITATY_KEY: ${AUF_CITATY_KEY}
    restart: on-failure:5
    networks:
      - auf-citaty-network
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis/redis-stack-server
    container_name: redis
    restart: on-failure:5
    networks:
      - auf-citaty-network
    ports:
      - "6379:6379"

networks:
  auf-citaty-network:
    