services:

  # Основной сервис

  auf-citaty:
    image: auf-citaty
    container_name: auf-citaty
    depends_on:
      - redis
    build: ./
    command: ./auf-citaty
    ports:
      - 8080:8080
    networks:
      - auf-citaty-network
    restart: on-failure:5

  # Redis

  redis:
    image: redis/redis-stack-server
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - auf-citaty-network
    restart: on-failure:5
  
# Кастомная сеть

networks:

  auf-citaty-network:
    